db.url=jdbc:postgresql://localhost:5432/classroom_economy
db.user=postgres
db.pass=YOUR_LINUX_DB_PASSWORD
brevo.api.key=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
